### ISSUE TITLE
[FEATURE, Oct 3rd, 2023]  - [PETPROGRAM] 식재료 탐험 페이지 조회 기능 구현

### ISSUE THREAD

**Issue by fakerdeft** [cocodaeng/cocodaeng-back#15]
# 설명
식재료 탐험 페이지에 필요한 데이터들 조회하는 기능 구현

# TODO
- [x] 펫 알러지 조회
- [x] 프로그램 알러지 조회
- [x] 처음 펫 등록 시 체크한 알러지를 바탕으로 해당 알러지들 보유한 프로그램 상태 미리 나쁨으로 등록
- [x] 펫이 진행중인 프로그램 전체 조회

# ETC
