### ISSUE TITLE
[REFACTORING, Oct 3rd, 2023] -[COMMON] 주석 생성 및 응답 표기법 통일

### ISSUE THREAD

**Issue by Subak-Uncle** [cocodaeng/cocodaeng-back#17]
# 설명
클라이언트에게 요청 반환 값을 제공해줄 때 표기법이 통일되지 않는 점을 확인. 
- 클라이언트 - 스네이크 표기법
- 서버 - 카멜 표기법
- DB - 스네이크 표기법
을 활용하면서 각 구간을 구분지을 예정

# TODO
- [x] 도메인 별 요청 값 표기법 수정
- [x] DB 테이블 칼럼 명 변경, 설명 작성
- [x] try/catch 문 작성

# ETC
