### ISSUE TITLE
[FEATURE, Oct 2nd, 2023]  - [PET] 펫 등록 

### ISSUE THREAD

**Issue by Subak-Uncle** [cocodaeng/cocodaeng-back#2]
# 설명
펫 등록 기능 구현

# TODO
- [x] DTO 설계
- [x] 사진 업로드
- [x] 견종 get 요청 api 설계
- [x] 유발 식재료 get 요청 api 설계
- [x] 펫 등록 post 요청 api 설계

# ETC
